disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "edelveis.dev"

[params]
  displayName = "EN"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
 # logo = "logo.png"
  # secondaryLogo = "img/secondary-logo.png"
description = "Java Developer Advocate. Tutorials, talks, and cyberpunk-flavored demos."
  # copyright = "Copy, _right?_ :thinking_face:"

 [params.author]
   name = "Catherine Edelveis"
   email = "catherine@edelveis.dev"
   image = "cat.jpg"
   imageQuality = 96
   headline = "Your friendly Java advocate: practical content, playful demos, serious wins."
#   bio = "Developer Advocate at BellSoft, tech writer, speaker, Java dev"
   links = [
     { email = "catherine@edelveis.dev" },
     { bluesky = "https://bsky.app/profile/cat-edelveis.bsky.social" },
#     { discord = "https://discord.gg/invitecode" },
     { github = "https://github.com/des-felins" },
#     { instagram = "https://instagram.com/username" },
     { linkedin = "https://linkedin.com/in/cat-edelveis" },
#     { medium = "https://medium.com/@cat.edelveis" },
#     { tiktok = "https://tiktok.com/@username" },
#     { twitch = "https://twitch.tv/username" },
     { x-twitter = "https://x.com/cat_edelveis" },
     { youtube = "https://www.youtube.com/@cbrjar" },
   ]
